[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/fleet"
  to = "/#fleet"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301
  force = true

[[redirects]]
  from = "/gift-cards"
  to = "/gift"
  status = 301
  force = true
